# Generated by Django 6.0 on 2025-12-17 02:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaBNCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código da Habilidade')),
                ('componente', models.CharField(max_length=50, verbose_name='Componente Curricular')),
                ('pratica_linguagem', models.CharField(max_length=200, verbose_name='Práticas de Linguagens')),
                ('habilidade', models.TextField(verbose_name='Habilidade')),
                ('objetos_conhecimento', models.CharField(max_length=255, verbose_name='Objetos do Conhecimento')),
                ('conteudos_relacionados', models.TextField(blank=True, null=True, verbose_name='Conteúdos Relacionados')),
                ('orientacoes_pedagogicas', models.TextField(blank=True, null=True, verbose_name='Orientações Pedagógicas')),
                ('descritores_saeb', models.TextField(blank=True, null=True, verbose_name='Descritores do SAEB')),
                ('feedback_nivel_1', models.TextField(help_text='Texto para Nível 1 (Não Desenvolvido)')),
                ('feedback_nivel_2', models.TextField(help_text='Texto para Nível 2 (Em desenvolvimento inicial)')),
                ('feedback_nivel_3', models.TextField(help_text='Texto para Nível 3 (Em desenvolvimento parcial)')),
                ('feedback_nivel_4', models.TextField(help_text='Texto para Nível 4 (Desenvolvido)')),
                ('feedback_nivel_5', models.TextField(help_text='Texto para Nível 5 (Plenamente Desenvolvido)')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano_letivo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('PROFESSOR', 'Professor')], default='PROFESSOR', max_length=20, verbose_name='Função')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado para Coordenação'), ('APROVADO', 'Aprovado')], default='RASCUNHO', max_length=20)),
                ('avaliacoes', models.JSONField(blank=True, default=dict)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='academic.turma'),
        ),
    ]
