# Generated by Django 6.0 on 2025-12-18 01:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código BNCC')),
                ('componente', models.CharField(choices=[('PORT', 'Língua Portuguesa'), ('ARTE', 'Arte'), ('EDFIS', 'Educação Física'), ('MAT', 'Matemática'), ('CIEN', 'Ciências'), ('GEO', 'Geografia'), ('HIST', 'História'), ('REL', 'Ensino Religioso')], max_length=10, verbose_name='Componente Curricular')),
                ('anos_aplicacao', models.CharField(help_text='Ex: 1EF, 2EF (Separados por vírgula)', max_length=100)),
                ('habilidade', models.TextField(verbose_name='Descrição da Habilidade')),
                ('prat_linguagens', models.TextField(blank=True, verbose_name='Práticas de Linguagens')),
                ('obj_conhecimento', models.TextField(blank=True, verbose_name='Objetos do Conhecimento')),
                ('cont_relacionado', models.TextField(blank=True, verbose_name='Conteúdos Relacionados')),
                ('or_pedagogicas', models.TextField(blank=True, verbose_name='Orientações Pedagógicas')),
                ('desc_saeb', models.TextField(blank=True, verbose_name='Descritores do SAEB')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMINISTRADOR', 'Administrador/Coordenador'), ('PROFESSOR', 'Professor')], default='PROFESSOR', max_length=20, verbose_name='Função')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('1', '1º Trimestre'), ('2', '2º Trimestre'), ('3', '3º Trimestre')], default='1', max_length=1)),
                ('ano', models.IntegerField(default=2025)),
                ('status', models.CharField(choices=[('RASCUNHO', '📝 Rascunho (Professor Editando)'), ('AGUARDANDO', '⏳ Aguardando Coordenação'), ('APROVADO', '✅ Aprovado (Finalizado)'), ('CORRECAO', '⚠️ Devolvido para Correção')], default='RASCUNHO', max_length=20)),
                ('feedback_coordenacao', models.TextField(blank=True, verbose_name='Feedback da Coordenação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('aluno', 'trimestre', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='SugestaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_alvo', models.CharField(choices=[('1', '1 - Não desenvolvido'), ('2', '2 - Em desenvolvimento (início)'), ('3', '3 - Em desenvolvimento (parcial)'), ('4', '4 - Desenvolvido'), ('5', '5 - Plenamente desenvolvido')], max_length=1, verbose_name='Sugerir para Nível')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição da Prática')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Aprovação'), ('APROVADO', 'Aprovado (Disponível)'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.competencia')),
                ('professor_autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Turma')),
                ('serie_curricular', models.CharField(choices=[('EI', 'Educação Infantil'), ('1EF', '1º Ano Fundamental'), ('2EF', '2º Ano Fundamental'), ('3EF', '3º Ano Fundamental'), ('4EF', '4º Ano Fundamental'), ('5EF', '5º Ano Fundamental')], max_length=5, verbose_name='Série (Currículo)')),
                ('ano_letivo', models.IntegerField(default=2025)),
                ('professores', models.ManyToManyField(blank=True, related_name='turmas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='academic.turma'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('1', '1 - Não desenvolvido'), ('2', '2 - Em desenvolvimento (início)'), ('3', '3 - Em desenvolvimento (parcial)'), ('4', '4 - Desenvolvido'), ('5', '5 - Plenamente desenvolvido')], max_length=1)),
                ('observacao_especifica', models.TextField(blank=True, verbose_name='Obs. desta competência')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.competencia')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.relatorio')),
            ],
            options={
                'unique_together': {('relatorio', 'competencia')},
            },
        ),
    ]
