# Generated by Django 6.0 on 2025-12-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField(default=2025, verbose_name='Ano Letivo Atual')),
                ('trimestre_ativo', models.CharField(choices=[('1', '1º Trimestre'), ('2', '2º Trimestre'), ('3', '3º Trimestre')], default='1', max_length=1, verbose_name='Trimestre Ativo')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configuração do Sistema',
            },
        ),
        migrations.AlterField(
            model_name='competencia',
            name='prat_linguagens',
            field=models.TextField(blank=True, verbose_name='Práticas de Linguagens/Unidade Temática'),
        ),
    ]
