# Generated by Django 6.0 on 2025-12-19 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_configuracaosistema_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='configuracaosistema',
            options={'verbose_name': 'Configuração do Sistema', 'verbose_name_plural': 'Configurações do Sistema'},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nivel',
            field=models.CharField(blank=True, choices=[('1', '1 - Não desenvolvido'), ('2', '2 - Em desenvolvimento (início)'), ('3', '3 - Em desenvolvimento (parcial)'), ('4', '4 - Desenvolvido'), ('5', '5 - Plenamente desenvolvido')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='academic.relatorio'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='anos_aplicacao',
            field=models.CharField(help_text='Ex: 1, 2, 3 (Números das séries separados por vírgula)', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', '📝 Rascunho (Professor Editando)'), ('ANALISE', '⏳ Aguardando Coordenação'), ('APROVADO', '✅ Aprovado (Finalizado)'), ('CORRECAO', '⚠️ Devolvido para Correção')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='sugestaoatividade',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Aprovação'), ('APROVADO', 'Aprovado (Disponível)'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='turmas', to=settings.AUTH_USER_MODEL, verbose_name='Professores da Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='serie_curricular',
            field=models.CharField(choices=[('1', '1º Ano Fundamental'), ('2', '2º Ano Fundamental'), ('3', '3º Ano Fundamental'), ('4', '4º Ano Fundamental'), ('5', '5º Ano Fundamental'), ('6', '6º Ano Fundamental'), ('7', '7º Ano Fundamental'), ('8', '8º Ano Fundamental'), ('9', '9º Ano Fundamental')], max_length=2, verbose_name='Série (Currículo)'),
        ),
    ]
